import{a as b,i as a,S as f}from"./assets/vendor-tnUJPedx.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&i(u)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const L="48427757-fc949e79797ba7e940d238484",E="https://pixabay.com/api/",w=15,g=async(e,r)=>{const o={key:L,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:w,page:r},{data:i}=await b.get(E,{params:o});return i},v=e=>`
    <li class="gallery-item">
        <a href="${e.largeImageURL}">
        <img class="gallery-img" src="${e.webformatURL}" alt="${e.tags}" />
        </a>
        <div class="info">
        <p class="info-item"><b>Likes:</b> ${e.likes}</p>
        <p class="info-item"><b>Views:</b> ${e.views}</p>
        <p class="info-item"><b>Comments:</b> ${e.comments}</p>
        <p class="info-item"><b>Downloads:</b> ${e.downloads}</p>
        </div>
    </li>
    `,y=e=>{if(!e||e.length===0){console.error("No images to render");return}const r=document.querySelector(".js-gallery"),o=e.map(i=>v(i)).join("");r.insertAdjacentHTML("beforeend",o)},S=document.querySelector(".js-search-form"),p=document.querySelector(".js-gallery"),l=document.querySelector(".js-load-more-btn"),c=document.querySelector(".loader");let d=1,n="",m=0;const q=async e=>{try{if(e.preventDefault(),n=e.currentTarget.elements.query.value.trim(),console.log("Search query:",n),n===""){a.error({title:"Error",message:"Please enter a search term"});return}d=1,m=0,p.innerHTML="",l.classList.add("is-hidden"),c.classList.remove("is-hidden"),l.removeEventListener("click",h);const{hits:r,totalHits:o}=await g(n,d);if(r.length===0){a.info({title:"No results",message:"No images found. Please try again."}),c.classList.add("is-hidden");return}m=o,y(r,!0),m>r.length&&(l.classList.remove("is-hidden"),l.addEventListener("click",h)),new f(".js-gallery a").refresh()}catch(r){a.error({title:"Error",message:"Something went wrong!"}),console.error(r)}finally{c.classList.add("is-hidden")}},P=()=>{const e=p.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})},h=async()=>{try{d++,c.classList.remove("is-hidden");const{hits:e}=await g(n,d);console.log("Fetched more hits:",e),e.length>0&&y(e,!1),new f(".js-gallery a").refresh(),d*15>=m&&(l.classList.add("is-hidden"),a.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."}),l.removeEventListener("click",h)),P()}catch(e){a.error({title:"Error",message:"Something went wrong!"}),console.error(e)}finally{c.classList.add("is-hidden")}};S.addEventListener("submit",q);
//# sourceMappingURL=index.js.map
